# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
site_name: Narwhal
site_url: https://nrwl.co
nav:
  - index.md
theme:
  name: material
  favicon: favicon.svg
  icon:
    logo: fontawesome/solid/fish-fins
    repo: fontawesome/brands/git-alt
extra:
  social:
    - icon: fontawesome/solid/envelope
      link: mailto:admin@nrwl.co

